### ISSUE TITLE
Integrating amplitude to segment without using cocoapod

### ISSUE THREAD

**Issue by Sh4rky** [segment-integrations/analytics-ios-integration-firebase#13]
Following the indication on this thread
https://github.com/segment-integrations/analytics-ios-integration-amplitude/issues/46#issuecomment-339481764

I integrated the files from `Segment-Firebase` project directly to my project and installed Firebase pod. It compiles well but if I try to integrate it using

```swift
let integration = SEGFirebaseIntegrationFactory.instance()
let configuration = SEGAnalyticsConfiguration(writeKey: self.segmentKey)
configuration.trackApplicationLifecycleEvents = true
configuration.use(integration)
```
as the documentation suggests but the result is in the attached image.
Any ideas?
Thanks in advance

<img width="417" alt="screen shot 2017-10-25 at 6 43 55 pm" src="https://user-images.githubusercontent.com/4087387/32057995-37c8b198-ba3f-11e7-8bd3-795b3c806d12.png">

**Comment by ladanazita** [comment]
Hi @Sh4rky, 

I'm a bit confused, I thought the issue was with Firebase, not Amplitude. Can you install Firebase as explained in the original issue you opened (by manually including the Segment-Firebase files) and integrate Segment-Amplitude via the cocoapods?

If you still encounter issues, could you share the complete crash stack trace?

Thanks!

**Comment by Sh4rky** [comment]
@ladanazita  Sorry I meant `Segment-Firebase` I've already edited it on the original comment.
I installed Firebase as explained in the original issue. And integrated Segment-Amplitud via cocoapods.
And that is the complete stack trace, it just keeps calling `dynamicDidFailToRegisterForRemoteNotificationsWithError` until it crashes.
<img width="330" alt="screen shot 2017-10-30 at 1 07 04 pm" src="https://user-images.githubusercontent.com/4087387/32181523-50de505c-bd73-11e7-859c-15442e2e87b1.png">
<img width="1030" alt="screen shot 2017-10-30 at 1 07 12 pm" src="https://user-images.githubusercontent.com/4087387/32181538-569b96d0-bd73-11e7-8aa0-ee4d1c98db16.png">

**Comment by ladanazita** [comment]
What other pods do you have? From what I can see, that doesn't seem to be coming from the Segment-Firebase nor the Segment-Amplitude

**Comment by Sh4rky** [comment]
Well if I remove 
`configuration.use(integration)`
it doesn't crash, or anything like it.

I have several dependencies as pods, not sure I can list them all as part of a public issue, I could send it on an email if needed. But it seems that it has to do with `SEGFirebaseIntegrationFactory` or `SEGAnalyticsConfiguration` not playing nice with `SEGFirebaseIntegrationFactory`

**Comment by Sh4rky** [comment]
@ladanazita researching it a little more it seems there is a collision with cordova Plugin `Pushwoosh`, removing it from my project seems to avoid the crash. 
Sadly that's not an option for our project.

**Comment by ladanazita** [comment]
@Sh4rky Sorry for the delay here. It sounds like this doesn't have much to do with this component then. Closing this out, but let me know if there is anything I can do to help!
Cheers
