### ISSUE TITLE
Enable installation via Carthage

### ISSUE THREAD

**Issue by radiodario** [segment-integrations/analytics-ios-integration-firebase#15]
We are using carthage for our stack (we are paying users of segment) and we are wondering what is the ETA for having installation available via Carthage

**Comment by radiodario** [comment]
at we have created a [Carthage compatible fork of the library](http://github.com/feeld/analytics-ios-integration-firebase), in case you need to use it

**Comment by ladanazita** [comment]
Hi @radiodario 

Thanks for this! We currently haven't had many users request Carthage support, but will keep it in mind to officially support it as we hear back from more customers.

Thanks again!
Ladan
