### ISSUE TITLE
Update podspec to support latest version of Firebase and Google Analytics 

### ISSUE THREAD

**Issue by yar1vn** [segment-integrations/analytics-ios-integration-firebase#29]
Our entire project is stuck behind because of this restriction with the Segment integrations with Firebase and Appboy. 

```
s.dependency 'Analytics', '~> 3.2'
s.dependency 'Firebase/Core', '~> 4.0'
```

**Comment by ladanazita** [comment]
@yar1vn Thanks for writing in! 

I'm assuming you would like the bump Firebase/Core from 4 -> 5, correct? We are looking into this, but as you can imagine a major version bump requires some time to understand the changes and make relevant updates to ensure we aren't impacting current instrumentations of Segment-Firebase for our customers.

I appreciate your patience here and will update here as soon as I have more!
Ladan

**Comment by bull-xu** [comment]
The latest version for Firebase is 6 now. Any possibility to update the dependency to have the latest Firebase?

**Comment by alanjcharles** [comment]
Firebase is now on `7.7` https://github.com/segment-integrations/analytics-ios-integration-firebase/blob/master/Segment-Firebase.podspec
