### ISSUE TITLE
Upgrade dependency to allow latest Firebase/Core

### ISSUE THREAD

**Issue by parrotbait** [segment-integrations/analytics-ios-integration-firebase#45]
Hi,

I have the Segment Firebase integration and it is blocking my upgrade to the latest Firebase Core. As per `pod dependencies` I can see:

```
- Segment-Firebase (2.4.0):
  - Analytics (~> 3.2)
  - Firebase/Core (~> 5.0)
  - Segment-Firebase/Core (= 2.4.0)
```

It is forcing 5.x.x version of Firebase Core. I need the latest Firebase due to a critical bug fix relating to push notifications. Firebase is now on 6.0.3 at time of writing. 

The only solution for me now is to remove the Segment Firebase integration so I can update to the latest Firebase, please update the integration.

**Comment by m-vdb** [comment]
same here, it's blocking our upgrade to React Native 0.60...

**Comment by benevbright** [comment]
Please update this..

**Comment by benevbright** [comment]
Maybe we can just use the forked version without `Firebase/core`'s version?

**Comment by benevbright** [comment]
Ok, 
This repo is not maintained. If you need it, fork the repo and edit `Segment-Firebase.podspec` file.
```
s.dependency 'Firebase/Core', '~> 5.0'
```
to
```
s.dependency 'Firebase/Core'
```

and use it from your `Podfile`
```
pod 'Segment-Firebase', :git => 'https://github.com/YOUR_GIT_TEAM/analytics-ios-integration-firebase.git', :branch => 'YOUR_BRANCH'
```

**Comment by Rickard80** [comment]
It's strange that this repo isn't maintained given the following:

> Using Segment’s Google Analytics mobile SDKs you could previously measure and optimize user engagement with your mobile-apps. On October 31st 2019, Google is sunsetting the Google Analytics mobile-apps reporting based on the Google Analytics Services SDKs for Android and iOS. This means all data collection and processing for properties that receive data from the Google Analytics Service SDK for mobile apps will stop. Google is deprecating Google Analytics in favor of Firebase SDKs. 
https://segment.com/docs/connections/destinations/catalog/google-analytics/

**Comment by alanjcharles** [comment]
Firebase has recently been updated. Please reach out to friends@segment.com if you are still running into issues.
