### ISSUE TITLE
Firebase screen events called from a secondary Thread

### ISSUE THREAD

**Issue by EdSancha** [segment-integrations/analytics-ios-integration-firebase#56]
I'm getting these warnings on the console: 

`2020-08-18 16:11:36.964061-0400 Chopra[1371:174800] 6.30.0 - [Firebase/Analytics][I-ACS025025] setScreenName:screenClass: must be called from the main thread to ensure that events are associated with the intended screen.`

I debugged it and it's definitely been called by a secondary thread inside Segment's library, is there anything we can do about this?

**Comment by EdSancha** [comment]
I think this is causing the library to not report custom ViewScreens to Firebase. Can someone look into this?
I'm in in:
* Analytics 4.0.4 (It also happened in 3.9) 
* Firebase Core 6.30
* Segment-Firebase 2.6.2

**Comment by bsneed** [comment]
This appears to have been fixed already.
