### ISSUE TITLE
Incompatible with Firebase Crashlytics

### ISSUE THREAD

**Issue by mplorentz** [segment-integrations/analytics-ios-integration-firebase#60]
I'm trying to implement the `Firebase/Crashlytics` CocoaPod due to the [sunsetting of Fabric Crashlytics](https://get.fabric.io/) and the fact that the old Fabric SDK will stop reporting crashes to Firebase on November 15th, 2020.

Like many others (#45, #29) I am having problems with the fact that `Segment-Firebase` requires a [version](https://github.com/firebase/firebase-ios-sdk/blob/24a58ad86ac9b86dfa4dc2a8bf03c754bb5f5076/FirebaseCore.podspec) of `Firebase/CoreOnly` that is more than a year old. In this instance I cannot just use an older version of the Pod I need,`Firebase/Crashlytics`, because it did not exist in August 2019 and requires a newer version of `Firebase/CoreOnly`.

Are there plans to update to a recent version of the Firebase SDK soon?

**Comment by Dfmarulanda** [comment]
Any update on this
@mplorentz is safe to clone your repo and work with it?

**Comment by mplorentz** [comment]
@Dfmarulanda no update, but my repo seems safe to clone. We're using it in our app and events are being routed correctly.

**Comment by mplorentz** [comment]
Looks like version 2.7.1 pins Firebase SDK 7.7.x, so this issue has been resolved.
