### ISSUE TITLE
Compatibility with Firebase Core 7.1.0

### ISSUE THREAD

**Issue by dngconsulting** [segment-integrations/analytics-ios-integration-firebase#63]
Last SegmentFirebase version available on Cocoapods supports only Firebase 6 (https://cocoapods.org/pods/Segment-Firebase). Is there any plan to support the last version which is the 7.1.0 ? https://firebase.google.com/support/release-notes/ios.

My app relies on Invertase 10.1 which supports this last version (https://github.com/invertase/react-native-firebase). And I'd want to use the  Segment Firebase integration (https://github.com/segmentio/analytics-react-native). 

For now I get this message with the current version : 
```
 [!] CocoaPods could not find compatible versions for pod "Analytics":
  In Podfile:
    RNAnalytics (from `../node_modules/@segment/analytics-react-native`) was resolved to 1.3.2, which depends on
      Analytics (~> 4.1)

    RNAnalyticsIntegration-Firebase (from `../node_modules/@segment/analytics-react-native-firebase`) was resolved to 1.3.2, which depends on
      Analytics

    RNAnalyticsIntegration-Firebase (from `../node_modules/@segment/analytics-react-native-firebase`) was resolved to 1.3.2, which depends on
      Segment-Firebase was resolved to 2.4.1, which depends on
        Analytics (~> 3.2)

CocoaPods could not find compatible versions for pod "FirebaseInstallations":
  In Podfile:
    RNAnalyticsIntegration-Firebase (from `../node_modules/@segment/analytics-react-native-firebase`) was resolved to 1.3.2, which depends on
      Segment-Firebase was resolved to 2.7.0, which depends on
        FirebaseAnalytics (~> 6.1) was resolved to 6.4.1, which depends on
          FirebaseInstallations (~> 1.1)

    RNFBCrashlytics (from `../node_modules/@react-native-firebase/crashlytics`) was resolved to 10.1.0, which depends on
      Firebase/Crashlytics (~> 7.1.0) was resolved to 7.1.0, which depends on
        FirebaseCrashlytics (~> 7.1.0) was resolved to 7.1.0, which depends on
          FirebaseInstallations (~> 7.0)

CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    RNAnalyticsIntegration-Firebase (from `../node_modules/@segment/analytics-react-native-firebase`) was resolved to 1.3.2, which depends on
      Segment-Firebase was resolved to 2.7.0, which depends on
        FirebaseAnalytics (~> 6.1) was resolved to 6.1.2, which depends on
          nanopb (~> 0.3)

    RNFBCrashlytics (from `../node_modules/@react-native-firebase/crashlytics`) was resolved to 10.1.0, which depends on
      Firebase/Crashlytics (~> 7.1.0) was resolved to 7.1.0, which depends on
        FirebaseCrashlytics (~> 7.1.0) was resolved to 7.1.0, which depends on
          nanopb (~> 2.30906.0)
```

Any clue ?

**Comment by patrick-samy** [comment]
I posted a similar issue this weekend and just added a potential workaround:
https://github.com/segment-integrations/analytics-ios-integration-firebase/issues/62#issuecomment-737918222

**Comment by dngconsulting** [comment]
Thanks for the workaround but I'd prefer a solution based on an "official" Segment package. In case of any side-effects related to incompatibilities it'll be easier to request support from Segment (or Firebase) 🙂

**Comment by danielhorv** [comment]
Please update the dependencies, we also need to use the latest Firebase SDK with Segment!

**Comment by maxbbb** [comment]
This is also a pretty big blocker for us as it's preventing upgrading the Segment Pod to >=4.0, which includes some pretty important changes for upcoming iOS 14 IDFA changes.

**Comment by alanjcharles** [comment]
Closing this as Firebase is now at `7.7`  https://github.com/segment-integrations/analytics-ios-integration-firebase/blob/master/Segment-Firebase.podspec
