### ISSUE TITLE
Swift Package Manager (SPM) Support

### ISSUE THREAD

**Issue by maherhanafi** [segment-integrations/analytics-ios-integration-firebase#64]
Hi,

Are you planning to support SPM moving forward?

Thank you

**Comment by kemalenver** [comment]
Fully support doing this.  My team have recently removed Carthage and CocoaPods from our project in favour of SPM 👍

**Comment by ztepsa** [comment]
Any news on this issue? Firebase supports SMP for a while now and it's working nicely.
Here's a link to [Firebase SPM docs](https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md).

**Comment by maherhanafi** [comment]
No news yet. We are trying to escalate to Segment via other channels

**Comment by Jeehut** [comment]
Would love to see this, Firebase is support SwiftPM now, this is the only library missing for us ...

**Comment by Jeehut** [comment]
I just posted a PR that's fixing this. Until it gets merged, feel free to use my fork by using `https://github.com/Jeehut/analytics-ios-integration-firebase.git` and pointing to the `master` branch.
