### ISSUE TITLE
Use of undeclared identifier 'config'

### ISSUE THREAD

**Issue by raboija** [segment-integrations/analytics-ios-integration-firebase#68]
Where exactly I'm supposed to write this line?

`[config use:[SEGFirebaseIntegrationFactory instance]];`

The documentation is unclear in this part, I'm a React Native engineer not very experienced in xcode.
I have `<Segment-Firebase/SEGFirebaseIntegrationFactory.h>` imported in` AppDelegate.m` and I wrote that line in the same file after doing pod install, but I get this error:

`Use of undeclared identifier 'config'`

Is there a file or function example where to put that line? Or I'm missing a simple import?

**Comment by zchwyng** [comment]
+1
