### ISSUE TITLE
Don't call [FIRApp configure] on behalf of user's application

### ISSUE THREAD

**Issue by shamilovtim** [segment-integrations/analytics-ios-integration-firebase#71]
This integration is not responsible for instantiating Firebase and to do so usurps authority from user's applications. Please remove calls that configure Firebase on behalf of users and allow users to configure Firebase themselves. 

The code that does this can be found here: https://github.com/segment-integrations/analytics-ios-integration-firebase/blob/f1da18d80bed7474b68eacd215adc635f10e31da/Segment-Firebase/Classes/SEGFirebaseIntegration.m#L33

**Comment by shamilovtim** [comment]
Can you please respond @bsneed

**Comment by bsneed** [comment]
I understand where you're coming from, but we can't change this unfortunately.  It has worked this way literally forever and to stop doing calling `[FIRApp configure]` now would break every other customer.
