### ISSUE TITLE
No shared framework scheme

### ISSUE THREAD

**Issue by SandeepAggarwal** [segment-integrations/analytics-ios-integration-firebase#8]
Dependency "analytics-ios-integration-firebase" has no shared framework schemes for any of the platforms: iOS

**Comment by ladanazita** [comment]
@SandeepAggarwal Can you provide more context here on the error you are seeing?

**Comment by SandeepAggarwal** [comment]
I am trying to use this library via Carthage and it is throwing the above mentioned error.

**Comment by ladanazita** [comment]
@SandeepAggarwal We don't support Firebase <> Carthage, and it looks like Firebase does not support Carthage natively as well according to [this issue](https://github.com/firebase/firebase-ios-sdk/issues/9).

Once that changes, I will be happy to look into supporting Carthage <> Firebase, but for now we can and will only support Cocoapods.
