### ISSUE TITLE
Cannot build the project when adding SegmentFirebase with Swift Package Manager, 'Segment/Segment.h' file not found

### ISSUE THREAD

**Issue by krris** [segment-integrations/analytics-ios-integration-firebase#84]
Hi 👋 

I added Segment (v4.1.6) and SegmentFirebase (v2.7.8) to the project with Swift Package Manager. Unfortunately, when building I got a build compilation error `'Segment/Segment.h' file not found`

I tried removing Derived Data, removing and adding dependencies again and it didn't help. Could you please guide me what could be an issue and how to fix it?

![Screenshot 2021-11-16 at 13 41 00](https://user-images.githubusercontent.com/1786612/141987457-99749128-8ad1-4caa-ba72-42cea675b8d5.png)
![Screenshot 2021-11-16 at 13 37 29](https://user-images.githubusercontent.com/1786612/141987461-1c6cac59-d946-48b3-aa8c-55104f5d2676.png)

Thanks!

**Comment by krris** [comment]
I've managed to fix this issue. Here's the pull request: https://github.com/segment-integrations/analytics-ios-integration-firebase/pull/85

**Comment by alexandreraulin** [comment]
Hi @bsneed, possible to release a new version with this fix please ?

**Comment by bsneed** [comment]
Fixed thanks to @krris!  Merged and released.
