### ISSUE TITLE
Increase version firebase core to 10.0.0 or higher

### ISSUE THREAD

**Issue by DaanVanRuijvenTide** [segment-integrations/analytics-ios-integration-firebase#94]
Firebase has released a new major version of its Core package 10. Users of this pod cannot upgrade their version of firebase core until this has been supported by this analytics-firebase integration

**Comment by julianfalcionelli** [comment]
The project I am working on needs this asap 🙏

**Comment by MichaelGHSeg** [comment]
Update to 10.2.0 in the latest release.

**Comment by julianfalcionelli** [comment]
Thanks @MichaelGHSeg !
