### ISSUE TITLE
Proposal to reduce download size.

### ISSUE THREAD

**Issue by yura-mv** [segment-integrations/analytics-ios-integration-firebase#97]
Instead of adding the whole Firebase package as dependency, can you include just the Analytics and Core frameworks as binary targets to reduce the download size?

**Comment by shamilovtim** [comment]
engineering best practices seem to not exist at Segment, unfortunately. we've raised half a dozen issues like this with them and they have all been met with indifference. our mobile team have opened many tickets that never get treated with any priority. even simple stuff like knowing what a peer dependency is. and if you point it out to them they close your ticket and act like they know what they're doing. our web team had to migrate off of their SDKs as a result of how little care they pay.

**Comment by bsneed** [comment]
Easy for you to say from your armchair @shamilovtim.  It's laughable to call "binary targets" engineering best practices.  Firebase updates so often and frequently, makes breaking changes outside of a major version bump.  The way it's being done is the most efficient way.  

We're not going to include binaries.
