### ISSUE TITLE
Debugin integratiuon

### ISSUE THREAD

**Issue by vrokida** [segment-integrations/analytics-ios-integration-firebase#98]
Hello ! 

My integration with Segment -> Firebase is not working ( I saw the events on Segment but nothing on Firebase console) and I did not get error.  

I am using: 
 cocopods with 
```
  pod 'Analytics', '~> 4.1'
  pod 'Segment-Firebase', '2.7.12'
```

code with Swift : 
```
 let configuration = AnalyticsConfiguration(writeKey: "MyKEY")
    configuration.trackApplicationLifecycleEvents = true 
    configuration.flushAt = 1
    configuration.recordScreenViews = true 
    configuration.use(SEGFirebaseIntegrationFactory.instance())
    Analytics.setup(with: configuration)
    Analytics.debug(true)
```
  And al also added the GoogleService-Info.plist file and on Segment I had enable the firebase destination
  
  
Questions please: 
Is there a way that can I check/debug if my configuration for firebase is ok? 
In the debug information the integrations json is empty , is this expected ? 
Could you provide me and example of use SEGAnalyticsIntegrationDidStart ? this example https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/ios-faqs/#how-do-i-know-when-a-destination-is-initialized does not compile in my side .

Thanks in advance

**Comment by bsneed** [comment]
Please contact support.
